### ISSUE TITLE
Default status should be closed, not open

### ISSUE THREAD

**Issue by yurug** [ocaml-sf/learn-ocaml#103]
Michele Pagani asks that the default status of exercise should be closed, not open. He is right.

**Comment by AltGr** [comment]
It really depends on your use-case: this is true when you intend to use assignments, but not in a textbook-style instance. Changing from one to the other is just a matter of 3 clicks on the teacher page:
- click on the "exercises" title to select all
- click open/close
- then validate

**Comment by yurug** [comment]
Yes! I discovered this magic hidden button last night by reading the code.

We should probably replace the label "exercises" by "exercises (click here to select all)" or a similar explicit signal.

**Comment by AltGr** [comment]
Yeah, I know it's not quite explicit!
Maybe a checkbox (`exercises ☐`) would at least hint that it's clickable.

**Comment by yurug** [comment]
Yes, let's try that!

**Comment by AltGr** [comment]
I am thinking that, besides highlighting, a checkbox in front of _all_ exercise and student lines would make the whole interface much easier to understand at first sight

**Comment by yurug** [comment]
I agree.
