### ISSUE TITLE
Teacher activity: Special characters in nicknames not displayed properly before sync

### ISSUE THREAD

**Issue by adhameer** [ocaml-sf/learn-ocaml#113]
When creating a new student token with the nickname "new test student", the student's name shows up in the student list in the teacher activity as "new%20test%20student". The issue is resolved after the student clicks the "Sync" button.

This also affects the downloaded CSV, and if the student closes the window and then logs in again on another machine, their nickname becomes "new%20test%20student".

**Comment by AltGr** [comment]
Ok, the problem seems to be on the encoding from the "create new account" form, I'll see to it. Thanks for reporting!
