### ISSUE TITLE
Internal error when syncing after assignment deadline

### ISSUE THREAD

**Issue by adhameer** [ocaml-sf/learn-ocaml#116]
When working on an exercise after the assignment deadline has passed, clicking the Sync button results in an Internal Error (Not Found). It would be nice to have something more user-friendly.

**Comment by AltGr** [comment]
That should not be the case indeed, I will check. The student should actually be allowed to sync, but the solution and grading report will be ignored (the toplevel input will still be saved). S/he is warned about this fact upon deadline expiration, or when re-opening the expired exercise.

To be sure, can you confirm that the student indeed has an assignement with an expired deadline ? If the assignment was removed altogether, the student will indeed no longer see the exercise in the list, and won't be allowed to open it. It shouldn't affect sync'ing, though...

**Comment by adhameer** [comment]
Yes, there is definitely an assignment with an expired deadline. When opening the exercise I get the message "The deadline for this exercise has expired. Any changes you make from now on will remain local only."

**Comment by AltGr** [comment]
Ok, thanks for the details
