### ISSUE TITLE
Add support for Markdown in exercises

### ISSUE THREAD

**Issue by Niols** [ocaml-sf/learn-ocaml#136]
Hey,

It would be great if we could write exercise descriptions directly in Markdown. This is usually much easier to write, read and correct than HTML. Moreover, because it's much more limited than HTML, it forces exercises to look the same.

I don't think it is hard to add to the project, especially considering that it is already implemented in `learnocaml_tutorial_parser.ml`. Here is a PR that tries to implement this feature if you are interested: #135.

Cheers,

**Comment by yurug** [comment]
This is implemented.
