### ISSUE TITLE
Syncing after deadline

### ISSUE THREAD

**Issue by wyschean** [ocaml-sf/learn-ocaml#138]
Currently, it is possible to continue working past the deadline and sync the grade if the browser is kept open at the exercise.

**Comment by AltGr** [comment]
Yes. The server won't register the new answers, though, as is shown in the dialog that should pop up at the deadline.

**Comment by AltGr** [comment]
(this may be a little misleading on the client-side because you can't see anymore the actual grade that you got. #122 actually helps with that, since it will give you the report as was submitted when re-opening the exercise)

**Comment by wyschean** [comment]
The grades that were synced this way showed up in the csv.

**Comment by AltGr** [comment]
was it within the 5 minutes after the deadline ? The server allows for a small "grace period"

**Comment by wyschean** [comment]
I think so. I'll report again if this happens again with a longer span of time.

**Comment by AltGr** [comment]
Rest assured I'll triple-check in the meantime :worried:
