### ISSUE TITLE
Prompt to refresh when server restarted

### ISSUE THREAD

**Issue by adhameer** [ocaml-sf/learn-ocaml#140]
When leaving an exercise open in a tab while the server is restarted, grading an exercise will use the old version of the grader and sync those results to the server with no notification to the student that the grader may have been updated. This is especially critical if we have restarted the server because we added additional tests to the grader.

It would be nice to have a pop-up when running the grader in this case saying something like, "The server has been updated, please refresh the page to make sure you are using the latest version of Learn OCaml (none of your work will be lost)."

It may be impossible to do something specifically when running the grader because I think that is all local, but running the grader calls sync as well, which makes a request to the server - maybe the information needed to check if the server has been restarted can be passed in the response?

**Comment by Asereme** [comment]
It would be possible to generate randomly a server ID during the building to check if it has been updated.
And a new request "ServerId" can be created in the API to get the current ID.

**Comment by EmileRolley** [comment]
Closed by #286
