### ISSUE TITLE
Button icons broken in newest docker image

### ISSUE THREAD

**Issue by adhameer** [ocaml-sf/learn-ocaml#141]
~~Trying to load the teacher activity results in the following Internal Error: `Could not decode server response: Json_encoding.Unexpected_field("creation_date")`~~

Okay, a hard refresh seems to have fixed it... but now the button images are broken for the save, restore, and sync buttons. The icons don't seem to be generated when the server is started. The issue only happens with the docker image and not when building from source.

**Comment by yurug** [comment]
I have fixed this issue on master yesterday and I thought the image was updated. It was not.

I am doing it right now.

**Comment by yurug** [comment]
The docker image has been updated. Can you confirm that the problem has gone?

**Comment by adhameer** [comment]
Yes, it's gone now. Thank you!
