### ISSUE TITLE
Global "Download" button

### ISSUE THREAD

**Issue by Armael** [ocaml-sf/learn-ocaml#162]
Currently, in order to save information to the local computer, the options are:

- a "Download" button which is local to an exercise (and saves the source code as a .ml file)
- a global "Save" button which produces a dump of the whole session as a .json file

It would be nice to have a global "Download" button that produces the set of all .ml files for all exercises. Currently the way to achieve this is manually pressing "Download" on each exercise, which is tedious.

**Comment by AltGr** [comment]
That could indeed be convenient. In the meantime, the command-line client can do it (using option `--fetch`)
