### ISSUE TITLE
CSS issue in teacher activity

### ISSUE THREAD

**Issue by adhameer** [ocaml-sf/learn-ocaml#163]
After the students are loaded in the student pane, the students heading overlaps the search box.

![image](https://user-images.githubusercontent.com/6691680/45831670-f89a9d00-bccd-11e8-9651-5dd6df683675.png)

**Comment by OCamlPro-Couderc** [comment]
Which browser are you using? I cannot reproduce it with Firefox (62) nor Chrome (69).

**Comment by yurug** [comment]
You need a long list of students to reproduce this bug AFAIK.
