### ISSUE TITLE
Better spot for the "prelude" code

### ISSUE THREAD

**Issue by Armael** [ocaml-sf/learn-ocaml#168]
The current location of the "prelude" code (bottom right of the screen) makes it hard to find.

It would be much nicer if it could be at the top of the text region where the user enters code. Also it would need to scroll with the rest of the code, so that it does not waste precious space in the editor (in case of a small screen).

**Comment by nobrakal** [comment]
@yurug This one was fixed by #254 , I think we can close it.

**Comment by yurug** [comment]
Thanks @nobrakal and @beobilly!
