### ISSUE TITLE
Support for grader code reuse

### ISSUE THREAD

**Issue by adhameer** [ocaml-sf/learn-ocaml#169]
We have a lot of functions that we are using repeatedly across graders for different exercises. Currently we have to just copy and paste those functions into `test.ml` for each grader since we don't have control over the build. It would be very nice if we could just put all this code into a separate module and link it during compilation.

(Maybe there is already a way to do this, but if there is, I'm not sure how.)

**Comment by yurug** [comment]
As far as I know, there is no way to do that in the current version. This is a good idea! Thanks!

**Comment by Niols** [comment]
I agree, it could be great to have this instead of copy-pasting everything all the time.

**Comment by fpottier** [comment]
On a related note, it would be nice if a grader could access certain common OCaml libraries (perhaps taken from a fixed set; or, ideally, declared by the grader itself). I am thinking for instance of `pprint`, but I am sure many others would be useful.

**Comment by fpottier** [comment]
Another library that I would like to use is `Seq`, which is standard in OCaml 4.07 and is emulated by an opam package in earlier versions. It is useful to program exhaustive enumerations of test cases.
