### ISSUE TITLE
Support for exercise code reuse

### ISSUE THREAD

**Issue by VLanvin** [ocaml-sf/learn-ocaml#174]
Exercises often require students to re-use functions they already have defined in a previous exercise. Currently (and to my knowledge), the only way to re-use previously defined functions is to either rewrite or copy-paste them (and all their dependencies). 

It would be nice if we could refer to a previous exercise via a module for example, so that we could write `Exercise2_1.my_sort_function l`.

Of course, a dependency check is needed to ensure that only the required exercises are compiled so as to let students do an exercise even if they skipped some before.

We could also have a module alias for every exercise, defined in the corresponding `meta.json`.

**Comment by EmileRolley** [comment]
Closed by #320
