### ISSUE TITLE
Sync code when going back to exercises list

### ISSUE THREAD

**Issue by VLanvin** [ocaml-sf/learn-ocaml#178]
When leaving an exercise by clicking on the "exercises" button at the top of the page, all non-saved changes to the code are lost. Could clicking on this button automatically trigger a synchronization of the changes before leaving the exercise?

**Comment by VLanvin** [comment]
It indeed works correctly on v0.8 on my computer.
I opened this issue because some of my students lost several changes by going back to the exercises list. I suppose this can be closed for now, and I will re-open it with more information if the problem reoccurs.

**Comment by AltGr** [comment]
Ok, thanks, please follow-up if anything happens again!
