### ISSUE TITLE
Printing unicode characters in the "Toplevel" page is broken

### ISSUE THREAD

**Issue by Armael** [ocaml-sf/learn-ocaml#197]
Displaying unicode characters does not seem to be working in the "toplevel" page. In particular, I defined a custom printer, that uses unicode characters. It works fine in the test reports, but not in the toplevel.
And additionally, the tooltip message at the top also contains broken unicode (for what I assume should be arrows).

![brokenunicode](https://user-images.githubusercontent.com/315125/48205360-6416f780-e36c-11e8-834a-419c7d3f3511.png)

**Comment by AltGr** [comment]
Just realised this last week. I have a fix but it's actually a bug in [js_of_ocaml](https://github.com/ocsigen/js_of_ocaml/pull/712). See https://github.com/ocaml-sf/learn-ocaml/pull/199/commits/97134af4f187729ef3479ce20859c6de62849c05

**Comment by Armael** [comment]
Thanks!!
