### ISSUE TITLE
Placement of toplevel clear/reset buttons

### ISSUE THREAD

**Issue by adhameer** [ocaml-sf/learn-ocaml#202]
It is really easy to click the clear/reset buttons in the toplevel by accident while trying to click into the text box to type some code. Maybe those buttons could be moved to the top-right corner or something... they aren't really buttons you would be clicking extremely often.

**Comment by nobrakal** [comment]
@yurug I think this issue can be closed

**Comment by adhameer** [comment]
I think it would be nice to have the Eval Phrase button on the right of the text box instead of in the top right with everything else. That would make it more clear what it actually does. It's not very intuitive to have it so far away from the text field.

**Comment by EmileRolley** [comment]
Closed by #261
