### ISSUE TITLE
Grading: giving negative points

### ISSUE THREAD

**Issue by adhameer** [ocaml-sf/learn-ocaml#207]
Sometimes we want to take off points from a student for making some mistake, but don't necessarily want to give the student points for _not_ making that mistake. This can currently be done by creating a `Success` report with a negative value, but the background of such a report is still green, which is confusing.

Checking whether the points value for a `Success` report is negative and changing the background colour accordingly could work, although the name "Success" would no longer make sense; and adding a points value to `Failure` reports would break a lot of existing code. Perhaps a new kind of status ("Penalty"?) could be added?

**Comment by yurug** [comment]
This is a great idea. Thank you @adhameer.

**Comment by Asereme** [comment]
Should the `Penalty` status be considered as a bad `Success` or a `Failure` ?
Or should we consider the function with penalty as `Complete` or `Imcomplete` ?

**Comment by adhameer** [comment]
My preference is for it to be considered as Failure, and the function with a penalty should be considered Incomplete.

**Comment by Asereme** [comment]
I have something like this.
![out](https://user-images.githubusercontent.com/50735325/60603977-09c51e00-9db7-11e9-932d-d3fb03970f0a.png)
Also, should we allow negatives points in a function or set a minimum of 0?
By default, an exercise has a minimum points of 0.
![out](https://user-images.githubusercontent.com/50735325/60605136-3da14300-9db9-11e9-8d4d-ec4a1b245bf8.png)

**Comment by adhameer** [comment]
Hmm. Is it possible to make the minimum score a per-section property? I can think of both cases where I would want the minimum score for a section to be 0 (such as in the example you have given) and where I would want the overall score for a section to be negative (for example, if I want to grade code style, I would probably have separate section called "Code Style" which might contain a `Penalty`, and I would like that grade deduction to be applied to the overall score for the exercise).

It would also be nice to have the point deduction indicated in another colour, maybe red to match the failures.

**Comment by erikmd** [comment]
I +1 this feature request.
In our assignments we have often used negative scores `n<0` associated to `Success n`, especially to implement a separate section related to "Code quality". E.g. if a student writes `if b then true else false` one or more times in the code (which is experimentally a very frequent pattern), he'll gets `-2` points or so, globally on the note.

So it'll be essential for us to keep the ability to have a section with a negative score [i.e., not imposing `max(0,⋅)`]

**Comment by Asereme** [comment]
To avoid breaking tests, I will create a new constructor `SectionMin of text * t * int` which will work as a Section with a minimum score.
![out](https://user-images.githubusercontent.com/50735325/60676969-8839c280-9e80-11e9-80ed-e305e088f138.png)
The state `Failed` will show up if the student has reached a minimum score or has a negative score.
By default, a `Section` will not have minimum.

**Comment by EmileRolley** [comment]
Closed by #292
