### ISSUE TITLE
learn-ocaml generates a javascript error

### ISSUE THREAD

**Issue by yurug** [ocaml-sf/learn-ocaml#21]
I know get the following error after building 73eace9ca778b7ec00c051adeac5d7a1a0390ae9

```
yann➜teaching/learn-ocaml/learn-ocaml(master)» learn-ocaml build --repo demo-repository                                                                                                                                                                                        [14:22:43]
Unimplemented Javascript primitive caml_pure_js_expr!
```

**Comment by AltGr** [comment]
I'll investigate, thanks for reporting

**Comment by AltGr** [comment]
This is apparently due to a regression in the latest version of `ocp-build`: make sure you have `1.99.19-beta` installed, and not `1.99.20-beta`. Opening an issue there, but in the meantime I filed #25 which should make us stick to the working version. Thanks for reporting!
