### ISSUE TITLE
Better control over visibility of prelude elements

### ISSUE THREAD

**Issue by fpottier** [ocaml-sf/learn-ocaml#215]
This is a feature request.

Currently, if I understand correctly, the code in `prelude.ml` is visible to the student, whereas the code in `prepare.ml` is not. Furthermore, `prepare.ml` can refer to (unqualified) names defined in `prelude.ml`, but *not* the other way around. This is too inflexible; for instance, I have an example where I need a type definition to be in `prelude.ml` (because the rest of the prelude depends on it) yet I would like it to be invisible (because I want the student to view this type as abstract).

Could we have finer-grained control over visibility? E.g., elements in `prelude.ml` could optionally be marked `[@invisible]`. (Perhaps, for the sake of symmetry, elements in `prepare.ml` could be marked `[@visible]`.)

**Comment by fpottier** [comment]
My current solution is to move everything into `prepare.ml` (so `prelude.ml` is empty) and explicitly copy the definitions that the student must know about into the exercise description in `descr.md`.

**Comment by adhameer** [comment]
I think the issue fixed by #254 was #168, not this one.

**Comment by nobrakal** [comment]
@yurug I think @adhameer is right, could you reopen this ?
