### ISSUE TITLE
Add a facility for testing a function against a postcondition

### ISSUE THREAD

**Issue by fpottier** [ocaml-sf/learn-ocaml#223]
The module `Test_lib` offers `test_function_1`, which compares an actual output against an explicit
expected output, and `test_function_1_against`, which compares an actual output
against the output of a reference implementation. We seem to be lacking
`test_function_1_post`, which would test whether an actual output satisfies a
user-specified postcondition.

Such a facility seems necessary when the specification is nondeterministic (i.e., when multiple outputs are correct).

At the moment, I have manually emulated this function using lower-level functions (`test_value`, `lookup_student`, `run_timeout`, etc.), but it would be preferable if the library offered this facility.

**Comment by adhameer** [comment]
+1 this, and in particular we would really like a way for testing a function against a postcondition _with respect to the original inputs_. Currently we've only been able to access the inputs to a particular test case by creating references that we update in `before_user` and it's very messy.

Here is an example, testing a two-argument function `f` with arguments `x` and `y`:

```
let test_f () =
  let x_ref = ref None in
  let y_ref = ref None in
  let unsafe_x () = match !x_ref with
    | None -> assert false
    | Some x -> x
  in
  let unsafe_y () = match !y_ref with
    | None -> assert false
    | Some y -> y
  in
  let update_refs (x, y, _) _ = x_ref := Some x; y_ref := Some y
  in
  let test v _ = (* v is the result of f x y *)
    let x = unsafe_x () in
    let y = unsafe_y () in
    (* some testing code involving v, x, y goes here *)
  in
  test_function_2_against_solution
    [%ty: int -> int -> int] "f"
    ~before_reference: update_refs
    ~test: (test_eq_ok test)
    ~gen: 10
    []
```
