### ISSUE TITLE
title.txt and meta.json

### ISSUE THREAD

**Issue by yurug** [ocaml-sf/learn-ocaml#26]
Is there a good reason that explains why the title is not store in the metadata file?

**Comment by AltGr** [comment]
I don't have the answer, but could try to do the change if it's better.

**Comment by lyrm** [comment]
I just tried the new meta.json and removed title.txt from my exercise directories : it works fine for the page with the exercises list but it give an error when I try to load an exercise : Learnocaml_exercise.Missing_field("title.txt").

**Comment by OCamlPro-Couderc** [comment]
@lyrm Okay, I have found the problem. I'll push a fix tomorrow. Thank you for reporting it!

**Comment by OCamlPro-Couderc** [comment]
Fixed in #64.
