### ISSUE TITLE
Litle bug on learn-ocaml-client create-token

### ISSUE THREAD

**Issue by leunam217** [ocaml-sf/learn-ocaml#271]
In the man section it says that LEARNOCAML_SERVER environment variable affects the result but when trying to use it  without --server it prompts asking for a server, even if just before one was set.

![Captura de pantalla -2019-06-12 17-57-44](https://user-images.githubusercontent.com/38218036/59367569-ab1efe00-8d3c-11e9-8628-b65f469f3ad9.png)

**Comment by nobrakal** [comment]
The `set-options` command does not set any environment variable (like `LEARNOCAML_SERVER`), it just writes down the configuration the configuration file.

Anyway, you are right, the client was not looking up in the configuration file for `create-token`, I will send a PR.
