### ISSUE TITLE
Re-add option --id to learn-ocaml-client-fetch

### ISSUE THREAD

**Issue by leunam217** [ocaml-sf/learn-ocaml#275]
In the current version of learn-ocaml-client there is no --id option anymore for the fetch command. I think this option is useful if the user have 5 exercises and wants just to download 1 file.

**Comment by nobrakal** [comment]
With the previous version, you were indeed able to specify `--id` with `--fetch`, but it was a bug: the `--id` option didn't have any impact, and the client downloaded all saves in all cases.

Anyway, this is a good feature, I will send a PR.
