### ISSUE TITLE
learn-ocaml-client: add more flexibility when there is not a config file

### ISSUE THREAD

**Issue by leunam217** [ocaml-sf/learn-ocaml#279]
When there is not a config file , print server and print-token don't work : a server and a token are asked interactively to set the configuration. It would be nice if the answer was nothing i.e "" meaning that there is not a token or server.

Thank you for your answers

**Comment by yurug** [comment]
I do not understand what you are suggesting in the second sentence of your first paragraph: why is it interesting to let the server address undefined?

**Comment by leunam217** [comment]
It would be interesting as if I want to use it i can set the server and set the token independently meaning that i can call the specific functions that I already have. Currently I'm fetching  both before setting the config file wich creates a third function. I have to admit that the functionality of the second paragraph is a caprice (moreover this will break the property of having a config file correct when having one).

But i think that the functionalities of  the first paragraph give value, as now the only way that i have to initialize the config file in all cases is to ask the user about the token and the server every time without giving the previous values. Because if i try to fetch the previous sever and there is not a config file, it will block the process because the program will ask to give a server.

I'm maybe explaining my idea badly, so if you have questions go ahead please

**Comment by leunam217** [comment]
By the way there is not the property  having a config file correct when having one as i say in my previous comment because it's possible to change the server without checking if the current token works for that server.

**Comment by leunam217** [comment]
> I do not understand what you are suggesting in the second sentence of your first paragraph: why is it interesting to let the server address undefined?

I'm sorry i didn't read correctly the question. I think it's interesting because it seems to me more natural to use. If i want to know how much something costs it doesn't mean i want to buy it. If i want to know what the current configuration is I don't want to be force to enter a configuration if it doesn't exists.

What do you think about my suggestion?

**Comment by leunam217** [comment]
I think to suit separation of concerns concept the best option is to throw an error.

**Comment by erikmd** [comment]
@yurug 
> why is it interesting to let the server address undefined?

I agree with @leunam217's suggestion: for the emacs client, it appears necessary to check whether there is already a server (resp. token) configured before proposing anything to the user. But with the current implementation, `learn-ocaml-client print-server` will require some user input if there is no existing config file, so the CLI call is blocking.

AFAICT, this is a bit similar to commands such as `git remote ls`, which will always terminate (possibly with an error code, if it is not run inside a repo).

What do you think?

**Comment by Asereme** [comment]
By default, when a `learn-ocaml-client` need to check the config file, it will ask by default to create one if no one exist in the user-wide (or local with `--local` option).

We can maybe force the user to create a config file only with a "init" command, like `learn-ocaml-client init` and print an error for the others commands that need it and suggest the "init" command.

**Comment by leunam217** [comment]
I'm working on a PR

**Comment by EmileRolley** [comment]
Closed by #299
