### ISSUE TITLE
learn-ocaml-client add different return values for template command 

### ISSUE THREAD

**Issue by leunam217** [ocaml-sf/learn-ocaml#280]
Same as #278.

**Comment by nobrakal** [comment]
Hi,

I am not sure to understand what you are requesting here. The `template` command fails with a value different of 0 if no id were provided, or if the id was not found on the server. I don't know if there is an other way of failing.

**Comment by leunam217** [comment]
![Captura de pantalla -2019-06-24 16-23-01](https://user-images.githubusercontent.com/38218036/60026812-9cb9d600-969c-11e9-931b-fe06b6c2fc63.png)

That is what i meant
