### ISSUE TITLE
Don't show Secret field if no secret is configured

### ISSUE THREAD

**Issue by adhameer** [ocaml-sf/learn-ocaml#303]
If no secret is configured for a server, ideally the Secret field should not be shown when creating a new token so that students are not confused about what this field is for.

**Comment by nobrakal** [comment]
Indeed !

@yurug Do you think I can change the API to replace the `Version` request by a more general `Info`, containing also if there is a configured secret?

**Comment by erikmd** [comment]
@adhameer 

> If no secret is configured for a server, ideally the Secret field should not be shown when creating a new token so that students are not confused about what this field is for.

Indeed! that's a very sensible suggestion.

@YoanwM will take a look at this enhancement, so I'm going to assign him.

> Do you think I can change the API to replace the `Version` request by a more general `Info`, containing also if there is a configured secret?

That would be possible indeed, but at first sight, if it's feasible to implement the hiding of the `Secret` field at server side (a bit like https://github.com/ocaml-sf/learn-ocaml/commit/1b25b04397bce5bb9fcf70827a280686f8089b3a), I'd prefer to keep the API as is :)
