### ISSUE TITLE
Progress bar for students is not displayed on a fresh repository

### ISSUE THREAD

**Issue by yurug** [ocaml-sf/learn-ocaml#314]
If a fresh empty /sync is used, the progress bars for students is not displayed.

@nobrakal suggests that this is due to the absence of `exercises.json`. This file can be created by changing the state of exercises from open to close, and to open again. Once this operation is done, the progress bars appear.

**Comment by erikmd** [comment]
Just FTR, this is related to this other open issue:

https://github.com/ocaml-sf/learn-ocaml/issues/337#issuecomment-571228304
