### ISSUE TITLE
(relatively urgent) check Docker Hub's automated build config for branch master

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#321]
Dear @yurug,

This issue is a follow-up of PR #313

## Description of the issue

Looking at https://hub.docker.com/r/ocamlsf/learn-ocaml-client/tags
I only see a tag `latest`, and no `dev` version corresponding to master:

![2019-10-04_00-44-19_Screenshot_learn-ocaml-client](https://user-images.githubusercontent.com/10367254/66169278-34d23e80-e640-11e9-9eaa-91a1d26bb6a6.png)

## Expected behavior

To sum up the suggested configuration of #313, the plan was that `latest` gathers automatic push of stable versions (a bit like `debian:latest` denotes Debian stable, not Debian testing or unstable) thanks to the related [hook](https://github.com/ocaml-sf/learn-ocaml/blob/master/hooks/post_push), and `dev` is updated much more frequently (in line with the tip of learn-ocaml's `master` branch).

So Yann, could you take a look at the page
https://cloud.docker.com/u/ocamlsf/repository/docker/ocamlsf/learn-ocaml/builds (URL blindly guessed) and check that `master` is indeed redirected to `dev`, not `latest`?

cf. the screenshot mentioned [in #313](https://github.com/ocaml-sf/learn-ocaml/pull/313#issuecomment-533263204):
![Screenshot](https://user-images.githubusercontent.com/10367254/65271828-31a66100-db1e-11e9-8978-8f2840236917.png)

(then this will be automatically tested when merging a new PR ;)

**Comment by yurug** [comment]
Dear @erikmd,

I actually remember writing "dev" in the docker tag in my first configuration but this was changed to "latest". If I try to replace "latest" by "dev" in the interface, and click on "save", I also get the replacement of "dev" by "latest".

**Comment by erikmd** [comment]
Dear @yurug,

I have just experienced a similar situation with https://hub.docker.com/r/pfitaxel/learn-ocaml :

- when the "rule" (associating the git branch and the image tag) is already created, one cannot change the tag itself;
- but *removing the rule with the bin icon, then adding it again (button `+`) with the other tag name seems to work* (the new setting is taken into account when clicking on `Save`)

Could you try this?

**Comment by erikmd** [comment]
(but if it doesn't work, one could report the bug on https://github.com/docker/hub-feedback/issues …)

**Comment by yurug** [comment]
I just followed this procedure and it seems to be working! Thanks @erikmd !

**Comment by erikmd** [comment]
Great! so I guess I can close this issue.
