### ISSUE TITLE
Part of input bar being covered by button

### ISSUE THREAD

**Issue by jiahao-c** [ocaml-sf/learn-ocaml#334]
When you hide the left panel,  a small portion of input bar will be covered under the "unhide" button.

![Screen Shot 2019-11-30 at 7 12 08 PM](https://user-images.githubusercontent.com/8275280/69907590-79125e80-13a5-11ea-9a27-b671a8a784fc.png)
![Screen Shot 2019-11-30 at 7 12 13 PM](https://user-images.githubusercontent.com/8275280/69907595-7adc2200-13a5-11ea-8e84-9beee54070c6.png)

**Comment by erikmd** [comment]
OK, closing this issue then; @jiahao-c feel free to reopen the issue if you think otherwise.
