### ISSUE TITLE
test_lib: testing functions (against a solution) modulo normalization/equivalence

### ISSUE THREAD

**Issue by gasche** [ocaml-sf/learn-ocaml#343]
A common need I have when writing graders is to accept some variability in the student results, typically for the ordering of elements in a list. (Consider the exercises `deduplicate : 'a list -> 'a list`, which removes all duplicates of any given value except (any) one of them, or `cartesian_product : 'a list -> 'b list -> ('a * 'b) list`, without requiring a lexical ordering.)

The current `Test_lib` API makes this rather inconvenient. I just spent a bit of time skimming it and found `Test_function_<n>_against_postcond` which makes it expressible, but I would expect the `_against_solution` variant to let me do this:
- we could have a `?normalize_output : ('b -> 'b)` parameter to normalize the output (by sorting it in a fixed way, typically)
- we could have a `?output_equiv : ('b -> 'b -> bool)` function to define a coarser equivalence between the solution's and the student's output
- or both :-)

Are those reasonable suggestions? Should I considering trying to send a PR to implement them?

(cc @fpottier and @adhameer who I guess have had to think about this problem already.)

**Comment by fpottier** [comment]
As far as I can see, `test_function_1_against_solution` (and other similar functions) take an optional argument labeled `test` which is a notion of equality between actual result and expected result.

That said, I usually don't use any of the high-level functions in the `Test_lib` API, because they are limited in various ways. For instance, they allow testing only one function at a time, whereas I often write tests that involve testing several functions together.

**Comment by gasche** [comment]
Ah, indeed, I had probably missed this argument. Thanks!

(To me `'b tester` suggests that this a unary testing predicate that passes or fails given an output value, not an equivalence function.)

**Comment by erikmd** [comment]
Hi @gasche

> A common need I have when writing graders is to accept some variability in the student results, typically for the ordering of elements in a list.

As outlined by @fpottier one can take advantage of the `~test` optional argument, and e.g. pre-sort the two lists at stake, and compare them with structural equality? I mean, by using this function:

https://github.com/ocaml-sf/learn-ocaml/blob/dd44150bbe46aab508ac3f4464fad5f36344bf6e/src/grader/test_lib.mli#L291-L295 

```ocaml
let canon x = List.sort compare x
let q_deduplicate =
  test_function_1_against_solution
    [%ty: int list -> int list]
    "deduplicate"
    ~test:(test_canon_ok canon)
    ~gen:5
    []
```

**Comment by gasche** [comment]
Thanks! I had missed `test_canon_ok` as well and was in the process of reimplementing it. Are those documented in the how-to-write-exercises documentation?

**Comment by erikmd** [comment]
@gasche Beyond the .mli ocamldoc comments I mentioned in my previous post, there is some documentation in this folder: https://github.com/ocaml-sf/learn-ocaml/tree/master/docs,
(which is intended to be available from http://ocaml-sf.org/learn-ocaml/ but indeed I've just noticed that the `Step n: […]` links are broken in page http://ocaml-sf.org/learn-ocaml/howto-write-exercises …)

so I guess for the moment the relevant files to look at are:
- https://github.com/ocaml-sf/learn-ocaml/blob/master/src/grader/test_lib.mli
- https://github.com/ocaml-sf/learn-ocaml/tree/master/docs
