### ISSUE TITLE
Implementing Exercises : error file ?

### ISSUE THREAD

**Issue by lyrm** [ocaml-sf/learn-ocaml#35]
Is there a way to test an exercises implementation (and especially the grader) without starting a server ? The error message are very imprecise (basically, it says FAILED).  

Or is there a log file somewhere with proper error messages ?

**Comment by yurug** [comment]
AFAIK, `learn-ocaml build` performs type checking so typing errors should be caught at this point.

Can you give us an example of an error uncaught by typechecking?

**Comment by AltGr** [comment]
Not sure exactly what you are after, but from the command-line, you can run:
```
learn-ocaml grade --exercises PATH_TO_REPO_EXERCISE --display-outcomes
```

See `learn-ocaml grade --help` for more options (and note that you can source `scripts/complete.sh` in bash/zsh to get completion of learn-ocaml's arguments)

**Comment by lyrm** [comment]
--display-outcomes is exactly what I want. Thanks !
