### ISSUE TITLE
[CI] What about migrating to GitHub actions?

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#358]
as mentioned in https://github.com/ocaml-sf/learn-ocaml/pull/356#issuecomment-651216508, some recent issues w.r.t. the PR status feedback from Travis → GitHub, and the stability of the macOS build on Travis CI make me wonder whether it'd be useful to switch learn-ocaml's CI to [GitHub Actions](https://help.github.com/en/actions).

@yurug do you have an opinion on that?

AFAICT, the features provided by GitHub Actions are quite nice, and maybe the [current](https://github.com/ocaml-sf/learn-ocaml/blob/master/.ci-macosx.sh) test [scripts](https://github.com/ocaml-sf/learn-ocaml/blob/master/tests/runtests.sh) could probably be reused with very few changes(?) − If need be I could have a look to prepare a PR, but not this week unfortunately :-/

**Comment by yurug** [comment]
That is something I was actually thinking about too. If you think you can prepare a PR to that end, that would be great!

**Comment by erikmd** [comment]
OK @yurug, thanks for your reply! I'll prepare a PR then

**Comment by erikmd** [comment]
@yurug the configuration I prepared is almost ready; I'll open the PR on this Wednesday.
