### ISSUE TITLE
The last Docker Hub build of `ocamlsf/learn-ocaml:dev` failed

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#360]
The logs of https://hub.docker.com/r/ocamlsf/learn-ocaml/ are not public but one can see in https://hub.docker.com/r/ocamlsf/learn-ocaml/tags that no successful build was pushed since the merge of #357

I investigated a bit more, reproducing the build in https://hub.docker.com/repository/docker/pfitaxel/learn-ocaml and I get:

<pre>
Processing 3/4: [learn-ocaml: dune build]
+ /home/opam/.opam/4.05/bin/dune "build" "-p" "learn-ocaml" "-j" "71" (CWD=/home/opam/.opam/4.05/.opam-switch/build/learn-ocaml.0.12)
<b>- js_of_ocaml src/toplevel/learnocaml_toplevel_worker_main.bc.js (got signal KILL)</b>
- (cd _build/default/src/toplevel && /home/opam/.opam/4.05/bin/js_of_ocaml +dynlink.js +toplevel.js --toplevel --nocmis -o learnocaml_toplevel_worker_main.bc.js --no-runtime /home/opam/.opam/4.05/lib/js_of_ocaml-compiler/runtime.js learnocaml_toplevel_worker_main.bc)
<b>- js_of_ocaml src/app/learnocaml_partition_view.bc.js (exit 1)</b>
- (cd _build/default/src/app && /home/opam/.opam/4.05/bin/js_of_ocaml +cstruct/cstruct.js -o learnocaml_partition_view.bc.js --no-runtime /home/opam/.opam/4.05/lib/js_of_ocaml-compiler/runtime.js /home/opam/.opam/4.05/lib/cstruct/cstruct.js ../ace-lib/ace_bindings.js learnocaml_partition_view.bc)
- warning: overriding primitive "caml_blit_bigstring_to_bigstring"
- old: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:16
- new: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:16
- warning: overriding primitive "caml_compare_bigstring"
- old: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:26
- new: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:26
- warning: overriding primitive "caml_fill_bigstring"
- old: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:37
- new: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:37
- warning: overriding primitive "caml_check_alignment_bigstring"
- old: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:47
- new: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:47
<b>- /home/opam/.opam/4.05/bin/js_of_ocaml: Error: Out of memory</b>
- js_of_ocaml src/app/learnocaml_description_main.bc.js
- warning: overriding primitive "caml_blit_bigstring_to_bigstring"
- old: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:16
- new: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:16
- warning: overriding primitive "caml_compare_bigstring"
- old: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:26
- new: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:26
- warning: overriding primitive "caml_fill_bigstring"
- old: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:37
- new: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:37
- warning: overriding primitive "caml_check_alignment_bigstring"
- old: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:47
- new: /home/opam/.opam/4.05/lib/cstruct/cstruct.js:47
- There are some missing primitives
[…]
</pre>

But I'm unsure how we could easily debug this (?) as locally, `docker build -t learn-ocaml .` is OK…
Cc @yurug @maiste FYI

**Comment by maiste** [comment]
Hi @erikmd,
sorry for my late reply! As you said, the problem comes from a memory limitation in the build system provided by Docker.  Before going on holidays, I was checking for a way to extend the memory space. Unfortunately, it seems that Dockerhub doesn't allow that to prevent RAM saturation on their servers.

I'm glad to know that moving to github CD/CI fixed this problem! Thanks so much!
