### ISSUE TITLE
404 on http://learn-ocaml.hackojo.org/

### ISSUE THREAD

**Issue by blandinw** [ocaml-sf/learn-ocaml#363]
http://learn-ocaml.hackojo.org/ returns a 404 Not found.

This link appears on the [website](https://ocaml-sf.org/learn-ocaml.html) and the [README](https://github.com/ocaml-sf/learn-ocaml/blob/master/README.md)

**Comment by gasche** [comment]
Ping @yurug : the website of the demo instance is down.

**Comment by yurug** [comment]
The new instance is here : https://ocaml-sf.org/learn-ocaml-public/

**Comment by gasche** [comment]
Thanks!

**Comment by gasche** [comment]
I made some publicity for the new instance over at <https://discuss.ocaml.org/t/interesting-ocaml-exercises-from-francois-pottier-available-online/7050>.
