### ISSUE TITLE
About the docker tag for master

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#367]
I recently realized that during the migration to GitHub Actions ([using the docker/build-push-action@v1 container action](https://github.com/ocaml-sf/learn-ocaml/blob/bcecadd9c01e3ee058a4c944e71af31019e48c78/.github/workflows/deploy-master.yml#L15)), I incidentally replaced the docker tag for master (formely called `dev`) with `master`.
This is due to this line: https://github.com/ocaml-sf/learn-ocaml/blob/bcecadd9c01e3ee058a4c944e71af31019e48c78/.github/workflows/deploy-master.yml#L23

This change (dev → master) was somewhat unintended, but on second thought it seems more coherent, when specifying the "version" label that is exposed in the images:
https://github.com/ocaml-sf/learn-ocaml/blob/bcecadd9c01e3ee058a4c944e71af31019e48c78/.github/workflows/deploy-master.yml#L19
as the git tag and the docker tag are now *the same string*.

However, this means there are now two docker tags for "the development version":
* `ocamlsf/learn-ocaml:master` which is now automatically up-to-date
* `ocamlsf/learn-ocaml:dev` which is obsolete (dates back to 29 June)

As a result, we should probably:
1. either untag the obsolete "dev" image (`ocamlsf/learn-ocaml:dev`) from Docker Hub & keep the current "master" deployment;
2. or untag the new "master" image and restore the "dev" deployment…

@yurug, your opinion on that choice?

If you choose solution 1., I guess you should just go to the following URLs and remove the `dev` old images:
https://hub.docker.com/repository/docker/ocamlsf/learn-ocaml/tags
https://hub.docker.com/repository/docker/ocamlsf/learn-ocaml-client/tags

**Comment by yurug** [comment]
@erikmd I chose solution 1 and removed the `dev` images. 
You are right that this is more consistent now.

**Comment by yurug** [comment]
I have updated the documentation accordingly in 42fdc082

**Comment by erikmd** [comment]
Hi @yurug, OK great!

but it seems there is a remaining occurrence of `:dev` here: https://github.com/ocaml-sf/learn-ocaml/blob/42fdc082d5fefe4c1b4d6f0a44aed58d34842a4a/docs/howto-deploy-a-learn-ocaml-instance.md

**Comment by yurug** [comment]
Thanks: I just replaced this last occurrence.
