### ISSUE TITLE
Support newer version of OCaml

### ISSUE THREAD

**Issue by Ailrun** [ocaml-sf/learn-ocaml#387]
As tools like ocaml-lsp, merlin, etc. stopped the support for OCaml 4.05, it becomes harder to use both offline environment and LearnOCaml based on needs.

It will be great if LearnOCaml updates to or somehow supports newer OCaml versions, like 4.12.

**Comment by yurug** [comment]
That's indeed something we plan to do in the close future.

**Comment by Ailrun** [comment]
Out of curiosity, what are the difficulties of the update? Maybe I can help to remedy some of those...

**Comment by erikmd** [comment]
Hi @Ailrun, thanks for opening this issue; actually the migration to a newer OCaml you suggest was already on our roadmap!

> what are the difficulties of the update?

basically, a large part of the codebase need to be refactored, including (but not limited to): the embedded toplevel, and the ppx support… given that both components are highly coupled with the version of OCaml!

The good news is that we now have an ETA for completing this migration: no later than July 2021, so definitely before the next Autumn term.
BTW I recently discussed this with @AltGr, who will start working on this migration in a couple of weeks, so I take the opportunity to mark him as assignee for this issue :)

**Comment by hannelita** [comment]
Hi folks!
@Ailrun and team, I tried updating the OCaml version at the McGill fork (https://github.com/teaching-the-art-of-fp/learn-ocaml), and the main issue was related to js_of_Ocaml. I had to bump the version we use, and it broke many parts of the toplevel.

**Comment by erikmd** [comment]
Hi @hannelita, thanks for your feedback!

Just to summarize/clarify, you're interested as well in migrating to OCaml 4.12 or so, but didn't finalize the migration IIUC.

In this case, I hope the fact that learn-ocaml only works with 4.05.0 for now is not a blocking issue for you…

anyway, when discussing with Louis, the announced ETA for July (maybe early July) did look feasible… but it's difficult to have a more precise ETA at the time :sweat_smile:

**Comment by AltGr** [comment]
Update on this (@gasche) due to the big pending PRs and to avoid too many conflicts, I've been asked to hold work on this as of yet; I still hope to be able to have it done before classes start in September.

**Comment by gasche** [comment]
Thanks for the update!

**Comment by AltGr** [comment]
Ok seems I'm catching up, ref. #408 :sweat_smile:

**Comment by erikmd** [comment]
Hi! #408 is now merged (to be released in upcoming learn-ocaml 0.13) so I guess I can close this issue now.

**Comment by erikmd** [comment]
In the meantime (just to recall), the continuously-deployed image `ocamlsf/learn-ocaml:master` now exposes a 4.12 toplevel.

**Comment by Ailrun** [comment]
Awesome, thank you for the notice!
