### ISSUE TITLE
Question: might we rename the `Try OCaml` button in Learn-OCaml's homepage?

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#415]
Hi all,

This is definitely not an urgent question, but I'm opening this issue to get more feedback:

currently (if most learn-ocaml features are enabled), we have the following buttons in the homepage:

![2021-09-01_Screenshot_Learn-OCaml_Home](https://user-images.githubusercontent.com/10367254/131590295-10a895fe-feff-4655-87de-72da76fbf5ba.png)

I see one potential issue with the first button `Try OCaml`:

* many users or students are familiar with [the Try OCaml webapp](https://try.ocamlpro.com/) and understand this term as `an online toplevel`,
* but this button actually redirects to the `tutorials` feature of Learn-OCaml, which can precisely be customized within the `repository/tutorials/` folder.

See e.g. the output of `learn-ocaml build --help`:

```
       --enable-tryocaml
           Enable the 'TryOCaml' tab (enabled by default if the repository
           contains a tutorials directory)
```

* On the other hand, the name of the `Toplevel` button and that of the `Playground` button (text-editor + toplevel) look fine.

### Hence the questions

1. Would you agree to rename this button? if yes:
  A. to `Tutorials`?
  B. to `OCaml Tutorials`?
  C. to another thing?

2. If we rename the button, should we also rename the option `--enable-tryocaml` to `--enable-tutorials`?

But actually I guess the answer to 2. should probably be no, for CLI backward-compatibility…

**Comment by erikmd** [comment]
Hi all (@AltGr @gasche @yurug @EmileRolley @hannelita @asere @lsylvestre and all the Watchers of this learn-ocaml repo :)

I know that this question is not critical at all; but if there is some consensus, we may want to include this small change for the upcoming [learn-ocaml 0.13](https://github.com/ocaml-sf/learn-ocaml/issues/418) as well (so feel free to react if you have an opinion on my 2 questions above 🙂)

**Comment by gasche** [comment]
No strong opinion, but I would find "tutorials" appropriate. You could add `--enable-tutorials` as a new option, and keep `--enable-tryocaml` for backward-compatibility.

**Comment by hannelita** [comment]
+1 for "Tutorials"

**Comment by erikmd** [comment]
Regarding this small question, thanks a lot for your feedback! no objection was raised, so +1 for @gasche's suggestion.

I'll open a PR but let's postpone this to learn-ocaml 0.14 (as it's not a critical User Story to appear in the pending 0.13 AFAICT).
