### ISSUE TITLE
Bug: partition-view does not work

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#438]
> Related issue(s) or PR(s): #421
> Related project scope(s) (ex: client, CSS, grading, etc...) : partition-view
> Related user(s): @erikmd @yurug

## Bug description

I tried using partition-view as described in #421 but I wasn't able to make it work with 0.12 nor with 0.13.0.

### To Reproduce

1. Go to Teacher dashboard
2. Middle-click
3. Put an existing function name
4. See error below (screenshot taken with 0.13.0)

### Expected behavior

No error

### Screenshots

![2021-10-07_01-12-46_Screenshot_partition-view_buggy](https://user-images.githubusercontent.com/10367254/136296153-b6b849ce-e547-4dcd-9c24-803b4fcb55c7.png)

## Current configuration

 - OS: GNU/Linux
 - Browser: Firefox
 - Version: ESR

**Comment by nobrakal** [comment]
It works on a fresh local installation. Do you have any details on your deployment ?

**Comment by erikmd** [comment]
Hi @nobrakal, sorry I was swamped with several deadlines; and I'm not sure we can fix this issue for 0.13.1;
so let's postpone this to next week with 0.14.0; I'll send you an e-mail meanwhile

**Comment by erikmd** [comment]
Hi @nobrakal, at last I got some time to create a minimal reproducible example, and actually the error appeared immediately after the steps below:

```bash
cd learn-ocaml
mkdir sync_repro
```
cf. its final contents in the attached .zip file: [sync_repro.zip](https://github.com/ocaml-sf/learn-ocaml/files/7467898/sync_repro.zip)

```
sudo docker run --rm -it -v "$PWD/sync_repro:/sync" -v "$PWD/demo-repository:/repository" \
  -p 8080:8080 ocamlsf/learn-ocaml:0.13.1
# Create two user accounts Alice & Bob.
# Code a correct version of the `times` function for the `demo` exercise.
# Login with the teacher account.
# Open the teacher dashboard.

# Partition the `times` function, which amounts to open:
firefox http://localhost:8080/partition-view.html?id=demo&function=times&prof=30
# → REQUEST ERROR; Could not retrieve data from server; URL not found: Error: Env.Error(_)

# Likewise:
firefox http://localhost:8080/partition/demo2/times/30?token=X-U1O-AB1-1FJ-ZOF
# → Error: Env.Error(_)
```

I took a quick look in the code, and I wasn't able to directly guess the location of the error…

@yurug plans to release 0.14.0 by the end of the week, so if you had the time to have a look, Alexandre, that'd be great!
Otherwise, no worries :)

**Comment by nobrakal** [comment]
Hi there, 

Thanks for the detailed example & procedure!

The example you gave me works when running a "local" LearnOCaml (installed with `make opaminstall`).
I have not tried the Docker installation, but the problem seems to lie there. I will try to investigate :)

**Comment by erikmd** [comment]
Hi @nobrakal, thanks for your feedback.

I believe I found the crux of the issue: regarding dependencies, partition-view → asak → compiler-libs,
but it happens that in the final Dockerfile (for minimization purposes), the opam switch is dropped,
while compiler-libs still needs `ocamlc` and the corresponding `$(ocamlc -where)` directory.
I've just pushed a patch that solves a similar bug in the on-going PR #458, and which maybe solves #438 as well
(did not test this latter thing)

**Comment by erikmd** [comment]
I've just tested the branch from #458, did `sudo make docker-images` then
`sudo docker run --rm -it -v "$PWD/sync_repro:/sync" -v "$PWD/demo-repository:/repository" -p 8080:8080 learn-ocaml`, and FYI the bug is indeed fixed.

Unfortunately, the fix increased the size of the server image:

```
sudo docker images
learn-ocaml                           latest                       c9e74cc38cc8   13 hours ago    869MB
ocamlsf/learn-ocaml                   0.13.1                       c3b1d8add5eb   3 weeks ago     103MB
```

**Comment by erikmd** [comment]
OK, so by tweaking my fix and adding just the three following lines in the Dockerfile:
```
ARG opam_switch="/home/opam/.opam/4.12"

COPY --from=compilation "$opam_switch/bin"/ocaml* "$opam_switch/bin/"
COPY --from=compilation "$opam_switch/lib/ocaml" "$opam_switch/lib/ocaml/"
```

we end up with:
```
$ sudo docker images | grep learn-ocaml
learn-ocaml                           latest                       72b68d29feaa   6 minutes ago   675MB
```

→ I'll merge this fix in master now (so `ocamlsf/learn-ocaml:master` will be working for people interested in this feature),
and we'll still be able to refine the fix later on if need be (if possible − but I'm unsure we can safely save much more MBs).

**Comment by nobrakal** [comment]
Many thanks for the fix :)
