### ISSUE TITLE
Bug: Unable to access inside "Actions" menubar button

### ISSUE THREAD

**Issue by asere** [ocaml-sf/learn-ocaml#444]
> Related issue(s) or PR(s): None
> Related project scope(s) (ex: client, CSS, grading, etc...) : Teach Tab in frontend
> Related user(s): most teachers/users of Learn-OCaml

## Bug description

This is a bug discovered by Nicolas Pécheux:
Clicking on "Actions" button in Teach Tab somehow show an empty list when clicking on it.
![image](https://user-images.githubusercontent.com/50735325/137131252-72525a61-0516-4e03-9658-2971dc880917.png)

From @asere:
I have tested on my side, and I get the expected behavior on my computer, but I get this bug on my phone.
Maybe this bug is linked to the responsive design.

### To Reproduce

1. Go to 'Teach' Tab
2. Click on 'Actions' button
3. Depending on your configuration, it may not show the list of possible actions.

### Expected behavior

The "Actions" button should show a list of possible actions (actually "Create a new teacher token" and "Download student data in CSV"). 
![image](https://user-images.githubusercontent.com/50735325/137130957-6950fd83-f8e7-4aab-acd0-cd9dae9d0296.png)

## Current configuration

 - OS: Mac OS Mojave 10.14.6
 - Browser Safari 14.1.2, Chome 94.0.4606.81 and Firefox 93.0

**Comment by erikmd** [comment]
Indeed @asere, it was precisely a responsive-mode related CSS bug.

Fixed in #450.

Meanwhile if you use a laptop/desktop, a trick to make the menubar show up amounts to typing <kbd>Ctrl + −</kbd> in the browser :)
