### ISSUE TITLE
More structures in exercises directories

### ISSUE THREAD

**Issue by lyrm** [ocaml-sf/learn-ocaml#45]
@AltGr will it be possible to add more structures (i.e. sub-(...)-directories) to the exercises ? Right now, this is basically flat and the teachers are structuring their exercises by naming properly the exercises directories (1.1 - 1.2 - 2.1 - 2-2). Being at least able to add one level ( 1/1 - 1/2 - 2/1 - 2/2) will be great.

**Comment by AltGr** [comment]
This is pretty simple; I have a 1-line patch to allow this (was just a missing 'mkdir'), but it relies on changes from #42, so waiting for it to be merged before filing a new PR.

**Comment by AltGr** [comment]
This was merged in 676214b40dfc1b3743094dbb8193e2eacd57f9ad
