### ISSUE TITLE
Blocking bug: some graders fail with `Error: Ctype.Unification_trace.Unify(_)`

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#457]
> Related project scope(s) (ex: client, CSS, grading, etc...) : grading
> Related user(s): @erikmd

## Bug description

I noticed this week a regression:
some graders of my lab sessions (relying on and extending code from `Test_lib`, so involving direct calls to `Introspection`) worked fine with 0.12 but now fail noisily with 0.13.x with the following error:

```
Learnocaml v.0.13.1 running.
Updating app at ./www
Exercise definition error while testing your solution:
File "_none_", line 1:
                                                       Error: Ctype.Unification_trace.Unify(_)


grader outcomes:
val print_html : 'a -> 'b = <fun>
module Code :
(…)
```

### To Reproduce

I was able to craft a minimal working example:

* Add just the following code in an existing `test.ml`:

```ocaml
module type tARITH_TEACHER = sig
  type t
  val zero : t
  val one : t
  val add : t -> t -> t
  val mul : t -> t -> t
  val opp : t -> t
  val of_int : int -> t
  val to_string : t -> string
end

(* dummy but sufficient example to reproduce the failure *)
let foo0 () = Introspection.get_value "INT" [%ty: (module tARITH_TEACHER)]
```

* then you'll get a failure with 0.13.1.

@AltGr, would you have an idea to isolate/fix the issue?

I hope this could be fixed or workarounded (so that the grader behaves the same as with 0.12).

## Current configuration

 - OS: GNU/Linux
 - Browser: Firefox
 - Version: learn-ocaml 0.13.1

**Comment by erikmd** [comment]
I skimmed the compiler-libs code, so it seems the error comes from a call to the `unify` function:

https://github.com/ocaml/ocaml/blob/46c947827ec2f6d6da7fe5e195ae5dda1d2ad0c5/typing/ctype.ml#L3114-L3121

But I can't see where the exception `Ctype.Unification_trace.Unify` would be un-caught in learn-ocaml's code after the 4.12 migration… hoping @AltGr will have some hints

**Comment by lsylvestre** [comment]
Hi @erikmd,
Hi @AltGr,

It seems that the bug occurs "statically" while the phrase is being loaded into the toplevel.
For instance, the following code :
```ocaml
let x = 10 ;;
let y = 11 ;;

let z = 12
and get = Introspection.get_value "x" ;;
```
produces the following trace :
```
Exercise definition error while testing your solution:
File "_none_", line 1:
                                                       Error: Ctype.Unification_trace.Unify(_)
...
module Test_lib : Test_lib.S
module Report = Learnocaml_report
val x : string = "foo"
val y : int = 10
demo                       [FAILED]

```
~> note that the name `z` is not loaded.

## Workarounded

Like this, it works :

```
module I = Introspection

let x = 10 ;;
let y = 11 ;;

let z = 12
and get = I.get_value "x" ;;
```


```
module Introspection = Introspection

module type tARITH_TEACHER = sig
  type t
  val zero : t
  val one : t
  val add : t -> t -> t
  val mul : t -> t -> t
  val opp : t -> t
  val of_int : int -> t
  val to_string : t -> string
end

let foo0 () = Introspection.get_value "INT" [%ty: (module tARITH_TEACHER)]
```

It's strange, isn't it?

So, to fix (temporarily) the problem, you can add the following code :

```ocaml
      handle_error (internal_error [%i"while preparing the tests"]) @@
      Toploop_ext.use_string ~print_outcome ~ppf_answer
        "module Introspection = Introspection" ;
      set_progress [%i"Launching the test bench."] ;
```

to the file : https://github.com/ocaml-sf/learn-ocaml/blob/master/src/grader/grading.ml#L143

have a good day,

Loïc

**Comment by erikmd** [comment]
Thanks a lot, @lsylvestre ! ✨ 

I'll merge your workaround now to be able to use `ocamlsf/learn-ocaml:master`;
(and we'll be able to refine the fix later on if need be - I added a comment in the code)
