### ISSUE TITLE
Bug: partition-view is unavailable on macOS

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#500]
**Related project scope(s):** UI

**Related user(s):** @erikmd et al.

## Bug description

In the teacher dashboard, the partition-view feature being triggered by a middle-click, macOS users can't use it.

### To reproduce

As described above.

## Additional context

- https://www.macg.co/logiciels/2020/02/middleclick-faites-un-clic-molette-avec-votre-trackpad-et-la-magic-mouse-111851
- https://github.com/artginzburg/MiddleClick-BigSur

**Comment by yurug** [comment]
One possible is to replace middle-click with ctrl+click : https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey#browser_compatibility
