### ISSUE TITLE
Bug: wrong number of spaces in displayed values in reports

### ISSUE THREAD

**Issue by jmadiot** [ocaml-sf/learn-ocaml#502]
**Related project scope(s):** UI, grading

## Bug description

In the Report tab, wrong or correct values are sometimes displayed with only one space instead of several spaces. This is a problem when the student's solution returns for example `"(1  +  2)"` instead of `"(1 + 2)"`.

### To reproduce

1. Go to [this exercise](https://ocaml-sf.org/learn-ocaml-public/exercise.html#id%3Dmooc/week1/seq3/ex2%26tab%3Deditor) that expects a string.
2. Type in `let sentence = "a   b"` (with three spaces between `a` and `b`)
3. Click "Grade!"
4. On the "Report" tab, the third line indicates "Wrong value `"a b"`"

### Expected behavior

The third line should indicate "Wrong value `"a   b"`" (with three spaces between `a` and `b`)

## Current configuration

* OS name (and version): N/A
* Browser 1: Firefox 107.0.1 (64-bit)
* Browser 2: Google Chrome Version 107.0.5304.110 (Official Build) (64-bit)
* `learn-ocaml --version`: 0.14.0
* `git describe --long --always --abbrev=40 --tags`: v0.14.0-15-ge55cf61bfb001a8aeeadb3dcd751825f1064e96e

## Additional context

Same problem if the value is correct.

However if the string representing the value has a newline in it (typically if the value is formatted into several lines), then the correct number of spaces is displayed.

The javascript object report displayed in the browser's console has the correct number of spaces.

**Comment by erikmd** [comment]
Thanks @jmadiot for the thorough bug report!

The bug should be fixed in master — and you'll be able to test it anew with either:

* `docker pull ocamlsf/learn-ocaml:master` (to be pushed in a couple of minutes)

* the static-binaries artifacts pinned to the last commit of the PR (see the last 3 checks among the "14 checks" of #503)
