### ISSUE TITLE
Question: useful to apply to the DSOS?

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#510]
### Question?

We may want to apply to https://www.docker.com/community/open-source/application/

Cc @yurug FYI

### What OS do you use?

GNU/Linux

### Additional context:

I think learn-ocaml complies with all the requirements of the Docker-Sponsored Open Source Program,
and the main benefit is to avoid docker pull rate-limits for all end users, for one year (to be renewed).

**Comment by yurug** [comment]
Done! 

![image](https://user-images.githubusercontent.com/448623/212494284-e9f5ccdd-99db-4d90-ba7e-80d304af2cfe.png)

**Comment by yurug** [comment]
Let's keep the issue open until we get the answer.

**Comment by erikmd** [comment]
Great! thank you @yurug 👍

**Comment by erikmd** [comment]
The application has been granted by Docker, Inc. to the project :tada:,
so let's close the issue now.

<details><summary>Screenshot</summary>

![2023-01-19_00-23-05_Screenshot_OSS](https://user-images.githubusercontent.com/10367254/213317243-b0716dcf-f0c9-45e6-95d9-7ae0bd74890e.png)

</details>
