### ISSUE TITLE
Feature: View synced (not graded) version of students' code

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#527]
### Related user(s):

@erikmd

### Related project scope(s):

teacher dashboard

### The problem:

Currently, the teacher dashboard only shows the submitted code of students after they click on `Grade`.

But if their code does not type-check, they won't be able to submit any code, and the teacher won't be able to help figure out the issue from the dashboard.

### Wanted solution:

* Add a `Draft` tab that shows the submitted code of students after they click on `Sync`.
* Put a different color than that of the `Answer` tab, e.g., light red, to account that this is ungraded code.

**Comment by erikmd** [comment]
Hi @Plictox !,
As soon as you feel that PR #540 is ready for review:

1. Let me know with a comment,
2. And feel free to start working on this feature request #527 (asking questions for any required clarification, of course)

Have a nice day.

**Comment by Plictox** [comment]
I think I am almost done. I still need to deal with the displaying of the info in the "details" tab, but for the "list" tab I should be ready for a review.

**Comment by erikmd** [comment]
Closed by 48583ba4d1376ad006227d7b5ee1b9cfaf9ad8f7 from PR #548
