### ISSUE TITLE
Feature: Ensure `learn-ocaml build serve` immediately handles requests at second run

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#529]
### Related user(s):

@erikmd

### Related project scope(s):

web-app UI, web API, build

### The problem:

* Currently, if we want to change an exercise description or solution or test, we restart `learn-ocaml build serve --repo=…`
* This rebuilds every exercise, which can be time-consuming;
* And in the meantime, the learn-ocaml backend is down (HTTP 502 Bad Gateway or so)

### Wanted solution:

* It would be nice to ensure that the server responds immediately at the second build, even if it needs to rebuild all exos.
* Then when the build is over, **atomically** set the newest directory as the one to be served.

### Considered alternatives:

* Does this require several threads? Would this benefit from OCaml 5?

**Comment by AltGr** [comment]
A possible alternative (not sure it's much simpler, but worth considering):

- keep the old instance running in the background (with a pidfile)
- run `learn-ocaml build serve --kill-previous-instance` that will
  * build into a new directory
  * kill the old server
  * swap the files
  * run the new server
