### ISSUE TITLE
Feature: rewrite URLs so that `%3D` chars are rendered as `=`

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#539]
### Related user(s):

@erikmd

### Related project scope(s):

web-app UI

### The problem:

When opening an exercise in a dynamic learn-ocaml server, the `=` chars are unexpectedly rendered as `%3D`:

* http://localhost:8080/exercises/tp1/#tab%3Dreport

### Wanted solution:

It would be nice to keep the `=` chars as is thanks to URL rewriting (if possible):

* http://localhost:8080/exercises/tp1/#tab=report

**Comment by Plictox** [comment]
If you agree I think I can do the same thing for the '&' character, as in this URL : http://localhost:8080/exercises/mooc/week1/seq3/ex1/#tab%3Dtext%26prelude%3Dshown

**Comment by erikmd** [comment]
@Plictox yes! that looks good.

**Comment by erikmd** [comment]
@Plictox FYI I did a few searches on MDN, and I have some news:

1. The culprit in learn-ocaml's code base is this code:

https://github.com/ocaml-sf/learn-ocaml/blob/1584a08636eb4ddb875a2b7051f78dbc94bec9b3/src/utils/js_utils.ml#L1201-L1204

2. Replacing `Url.Current.set_fragment fragment` with `Dom_html.window##.location##.hash := Js.bytestring s` solves the issue.

3. FTR, the `location.hash` is documented at https://developer.mozilla.org/en-US/docs/Web/API/Location/hash 

4. There was a bug w.r.t. encoding/decoding only for the *getter* (see e.g. https://stackoverflow.com/questions/1703552/encoding-of-window-location-hash ), but AFAICT, it is unneeded to url-encode before calling the *setter*.

So I assign @AltGr and myself for now, we'll see at our next maintainer telco (end-May) if we propose a patch upstream to simplify `Url.Current.set_fragment`
