### ISSUE TITLE
Grade incomplete solutions?

### ISSUE THREAD

**Issue by Eemency** [ocaml-sf/learn-ocaml#58]
I’m writing a program intended to check the validity of the tests proposed by the teachers.

The idea is to have them write several “essays”, that are more or less correct copies of students inside an `essay` directory inside each exercise directories. Each essay will be associated to the grade the teacher expects a student to have for this essay.
Then, the program would grade them to see if the expected grade matches the generated one. The goal is to detect errors in the test function or in the solution.

I’m using the `grade` functionality of the `learn-ocaml` command. Sadly, I didn’t find a way to fetch the score obtained by a graded essay (with `--grade-student`). For example, if I use `learn-ocaml grade --display-progression` in the exercise directory, I get full points as the solution is tested, which is correct. That also gets printed on the screen. Same if I grade a correct solution. But if I grade an incorrect solution, I only get “Failure” and no more informations, even though some answers are correct. The generated grade misses, so I can’t check it against the defined one.

To put it in a nutshell, I think it would be interesting to give the grade obtained when using `grade` from the command line instead of just outputting “Failure”.

**Comment by AltGr** [comment]
The interface of the `grade` command is indeed quite rough (ported directly from the old `learnocaml-grader` exec) and clearly needs to be rewritten. Adding this to the to-do list.

Related to #41 in this regard.

**Comment by EmileRolley** [comment]
Closed by #63
