### ISSUE TITLE
Fonts are missing

### ISSUE THREAD

**Issue by yurug** [ocaml-sf/learn-ocaml#77]
After a fresh installation of learn-ocaml, I get that:

![screen](https://user-images.githubusercontent.com/448623/44155778-78a48a38-a0ae-11e8-907b-351f064f0d78.png)

**Comment by AltGr** [comment]
The missing fonts make sense (our favorite font has a complex license that doesn't make it clear we can redistribute it with the source, check in the `static/fonts/` subdirectory to manually include it) ; but the CSS is normally configured with sane fallbacks. This is mentionned in the [License and Copyright](https://github.com/ocaml-sf/learn-ocaml#license-and-copyright) section of the README.

The `replace is not a function` error seems more worrying to me, do you know where it comes from?

**Comment by yurug** [comment]
Hmm, no. This is the first time I meet this one.

My version of js_of_ocaml is 3.2.1.

**Comment by yurug** [comment]
The web user interface is out of order. However, I can interact with the server using `learn-ocaml-client`.

**Comment by yurug** [comment]
Isn't it strange that opam installed 3.2.1 instead of 3.1.0 given that I followed the installation procedure to install learn-ocaml's opam dependencies?

**Comment by OCamlPro-Couderc** [comment]
Did you update you opam environment recently? It might be related to js_of_ocaml "sub" packages (js_of_ocaml-lwt for example) not in the sync, i.e. with a different version than js_of_ocaml. I had the same issue once, after an opam update.

**Comment by yurug** [comment]
Thanks @OCamlPro-Couderc, that might be the case indeed!

**Comment by yurug** [comment]
There is something weird in my opam installation. Look:

```
ann➜teaching/learn-ocaml/learn-ocaml(docs-classroom)» opam install js_of_ocaml.3.1.0         [9:43:23]
[NOTE] Package js_of_ocaml is already installed (current version is 3.1.0).
yann➜teaching/learn-ocaml/learn-ocaml(docs-classroom)» js_of_ocaml --version                  [9:43:27]
3.2.1
yann➜teaching/learn-ocaml/learn-ocaml(docs-classroom)» which js_of_ocaml                      [9:43:33]
/home/yann/git/teaching/learn-ocaml/learn-ocaml/_opam/bin/js_of_ocaml
yann➜teaching/learn-ocaml/learn-ocaml(docs-classroom)» _opam/bin/js_of_ocaml --version        [9:43:43]
3.2.1
yann➜teaching/learn-ocaml/learn-ocaml(docs-classroom)» echo $PATH                             [9:44:03]
/home/yann/git/teaching/learn-ocaml/learn-ocaml/_opam/bin:/home/yann/usr/bin:/home/yann/.opam/4.05.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

**Comment by AltGr** [comment]
Pff, that's really on the js_of_ocaml package maintainers...
I had a PR for this but only fixed part of the missing constraints.
@yurug, can you check `opam list js_of_ocaml\*` ?

**Comment by yurug** [comment]
Things are getting stranger:

```
» opam list js_of_ocaml\*                                       
# Packages matching: (installed | available) & name-match(js_of_ocaml*)
# Name                        # Installed # Synopsis
js_of_ocaml                   3.1.0       Compiler from OCaml bytecode to Javascript
js_of_ocaml-camlp4            3.1.0       Compiler from OCaml bytecode to Javascript
js_of_ocaml-compiler          3.2.1       Compiler from OCaml bytecode to Javascript
js_of_ocaml-lwt               3.1.0       Compiler from OCaml bytecode to Javascript
js_of_ocaml-ocamlbuild        --          Compiler from OCaml bytecode to Javascript
js_of_ocaml-ppx               3.2.0       Compiler from OCaml bytecode to Javascript
js_of_ocaml-ppx_deriving_json --          Compiler from OCaml bytecode to Javascript
js_of_ocaml-toplevel          3.2.0       Compiler from OCaml bytecode to Javascript
js_of_ocaml-tyxml             3.2.0       Compiler from OCaml bytecode to Javascript
```

**Comment by yurug** [comment]
```
opam install js_of_ocaml-compiler.3.1.0
```
fixed the problem.

We probably should fill an issue on the js_of_ocaml-compiler side and declare this specific version of the compiler package in our opam file.

**Comment by AltGr** [comment]
So this explains that: it's indeed the broken dependency constraints in opam-repository that led you to have inconsistent versions of the various jsoo packages, leading to a broken install.

`opam install js_of_ocaml-compiler.3.1.0 js_of_ocaml-ocamlbuild.3.1.0 js_of_ocaml-ppx.3.1.0 js_of_ocaml-toplevel.3.1.0 js_of_ocaml-tyxml.3.1.0` should fix it manually

**Comment by hhugo** [comment]
It seems to me that the issue is not with inter-dependencies but with js_of_ocaml-compiler.3.2.1 itself.
@AltGr, why do you think different versions matter here?

**Comment by AltGr** [comment]
Err, I don't know actually, maybe I jumped to conclusions. Just tried upgrading all to their latest versions, and the problems seem to be gone, though.

**Comment by josprachi** [comment]
> ocamlbuild

 -use-ocamlfind \
  -plugin-tag "package(js_of_ocaml.ocamlbuild)" \
  -no-links \
  main.d.js
+ ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package js_of_ocaml.ocamlbuild myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
ocamlfind: Package `js_of_ocaml.ocamlbuild' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 10

> 
I am getting this error when i try to run make command
