### ISSUE TITLE
Feature request: basic authentication at exercise level

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#80]
Dear learn-ocaml developers,

I'd like to suggest implementing some feature to ease the following use case:
- undergraduate students use (the same instance of) a learn-ocaml server during the lab sessions
- they have to work on a given learn-ocaml exercise (the main exercise of the week)
- all students are separated in several groups (viz., with *at least 5 different schedules* during the week)
- we'd like they can access this exercise only **starting from the time slot of their own lab session**
- indeed even if the exercise is not formally graded, we would like to put all the students all on an equal footing, despite the different schedules.   

Obviously a complex feature of «student individual authentication» combined with a «list of authorized exercises by student group» would address this... but maybe a simpler solution such as a basic authentication feature would suffice and be worth it to implement?

In particular I was wondering whether one could **add an optional token** (corresponding e.g., to the hash of a password) **to the metadata of an exercise** so that on the JavaScript side, the learn-ocaml client asks a password to the student and compares its hash with the one specified in order to unlock the exercise…

What do you think?

**Comment by erikmd** [comment]
OK awesome! :) and if ever you could implement this before September 17th, that would be really great! :smiley:

**Comment by AltGr** [comment]
You can check out the newer versions, which do implement a "teacher" view of exercises, students, and allows to create assignments. Feedback on the UI welcome, I tried to make something functional but GUIs are not my strong suit.

Controls to sort and filter students are still to be done.

**Comment by erikmd** [comment]
Hi @AltGr, sorry for not replying earlier.
I've just had some time to test the current `dev` docker image, it indeed fully addresses my wishlist #80! :)
Thanks for the impressive work :+1:
