### ISSUE TITLE
Suggestion (enable Travis CI) & Fix (required version of OCaml)

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#9]
Hi,

Would you have an objection to enabling continuous integration using Travis CI? The repo already contains a `.travis.yml` file, so I guess it would suffice to enable the GitHub/Travis-CI integration… (BTW since a few days, [the URL of Travis' plaform for open source projects is now travis-ci.com](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps?utm_source=Intercom&utm_campaign=2may_release) instead of travis-ci.org…)

Unrelated remark: since be0e079a4a8a7eeb7f8a1488e0f296b4b3d6a209, shouldn't the line
```
Note: you need a working opam environment with OCaml 4.03.0.
```
in the README.md be replaced with
```
Note: you need a working opam environment with OCaml 4.05.0.
```
? (Compiling with 4.03.0 raises the error `learn-ocaml-deps is not available because your system doesn't comply with ocaml-version >= "4.05.0".`)

Kind regards, Erik

**Comment by yurug** [comment]
The second part of this issue is taken care of here: 8d7d58936363899956e205c2143c8f28336a5236

**Comment by yurug** [comment]
Travis support will come soon.

**Comment by AltGr** [comment]
I have a working CI script on my fork that works: see https://travis-ci.org/AltGr/learn-ocaml

It's based on the Docker script, so checks at least that the program builds and runs on the demo repository. Running the server and verifying a few requests could be a further step, but properly testing a web-app is much more involved.

Can someone with admin rights enable Travis on this repo, so that these tests take effect once I clean my branch up and merge ?

**Comment by yurug** [comment]
This should work now:
https://travis-ci.org/ocaml-sf/learn-ocaml

**Comment by AltGr** [comment]
Thanks! Could you also enable runs on pull-requests ? It's always better to know if things go wrong before merging :)

**Comment by yurug** [comment]
This option seems already activated, am I wrong?

**Comment by OCamlPro-Couderc** [comment]
The CI seems be be working on pull requests (see #44), maybe we can close this issue.

**Comment by erikmd** [comment]
@OCamlPro-Couderc I don't think so: IINM it seemed to work for #44 because it was a PR created from an upstream branch (not a branch from a fork). And if you compare this PR and for example 
https://github.com/bcpierce00/unison/pull/134#event-1444951234
you see in the latter that you have

    2 checks passed
    continuous-integration/travis-ci/pr — The Travis CI build passed
    continuous-integration/travis-ci/push — The Travis CI build passed 

while in #44 there is only one check

    continuous-integration/travis-ci/push — The Travis CI build passed

so the downside is that in this case, the codebase tested by Travis CI is just the source branch, not the codebase of the target branch after an hypothetical merge of the PR.
So maybe we can reopen this issue? :)

**Comment by yurug** [comment]
I have enabled a new option on the travis-ci.

**Comment by erikmd** [comment]
Hi @yurug! indeed according to #46 the travis pr build now appears to be enabled, so I'm closing #9 :)
